### ISSUE TITLE
Error when trying to load data

### ISSUE THREAD

**Issue by MartinDelille** [HackBil/jeudizza#14]
Following the readme, I have the following error:

```
./manage.py loaddata seed.json
Traceback (most recent call last):
  File "/Users/martin/dev/clone/jeudizza/.v_env/lib/python3.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/martin/dev/clone/jeudizza/.v_env/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: django_content_type
```

**Comment by Amoki** [comment]
This project has not been maintained for many years. I definitely didn't expect an issue :p 

If you to `./manage.py migrate` before the loaddata, does it work?
